### ISSUE TITLE
GitHub pages?

### ISSUE THREAD

**Issue by bblanchon** [git-no/jekyll-breadcrumbs#10]
Hi!

I managed to get the breadcrumbs working on my computer; however, it's missing when I push to GitHub pages.

Is it possible to use this plugin with GitHub pages?

Regards,
Benoit

**Comment by git-no** [comment]
Have to check it. Because of the coming holiday it can take some time. But interesting issue, have to dig into.

**Comment by bblanchon** [comment]
I've checked and GitHub Pages only allows plugins from a whitelist, so it's no possible to use this plugin :-(

PS: [I found a solution that works on GitHub Pages](https://blog.benoitblanchon.fr/semi-automatic-breadcrumbs-for-github-pages/).
