### ISSUE TITLE
root level documents are not nested in breadcrumbs

### ISSUE THREAD

**Issue by inetbiz** [git-no/jekyll-breadcrumbs#13]
https://legaldemo.strikehawk.com/contact.html I'm trying to make Home/Contact be the breadcrumb. What am I doing wrong? I followed the directions.

**Comment by git-no** [comment]
> https://legaldemo.strikehawk.com/contact.html I'm trying to make Home/Contact be the breadcrumb. What am I doing wrong? I followed the directions.

It seems to me "Contact" is a list item and part of the breadcrumb. But it has no link.
If you want to have a link for the last breadcrumb item, add href to the last item of the loop, edit this file to your needs:
[https://github.com/git-no/jekyll-breadcrumbs/blob/master/site/_includes/nav-breadcrumbs.html](https://github.com/git-no/jekyll-breadcrumbs/blob/master/site/_includes/nav-breadcrumbs.html)
