### ISSUE TITLE
Support baseurl

### ISSUE THREAD

**Issue by jaybrueder** [git-no/jekyll-breadcrumbs#8]
Hi,

I am using the `baseurl` setting in my `_config.yml`:

```
baseurl: /blog
```

With this plugin, the setting is not being picked up. All breadcrumbs are being generated without the `baseurl`.

**Comment by jaybrueder** [comment]
This can be fixed by accessing the `baseurl` inside the plugin:
`side.site.baseurl`.

I will submit a PullRequest!

**Comment by git-no** [comment]
The new version (released today as beta) should support baseurl. Did work within my tests.
If the new version does not work with you do not hesitate to send me a message.
