### ISSUE TITLE
Exclude the home page from breadcrumbs

### ISSUE THREAD

**Issue by svetlanapuro** [git-no/jekyll-breadcrumbs#9]
Hi there,

Is there any way to exclude the home page from breadcrumbs? For example, I have the following structure:

```
Home / Knowledge base / Post
```

I would like to keep only:
```
Knowledge base / Post
```

**Comment by git-no** [comment]
Hello,

Yes, it is. 
Edit the _includes/nav-breadcrumbs.html file:
Remove the html code within the ```if forloop.first```clause.
